/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.aod;

import java.io.IOException;
import java.util.ArrayList;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiProperties;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.DocumentType;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import android.os.AsyncTask;

@Kroll.module(name = "Aod", id = "ti.aod")
public class AodModule extends KrollModule {

	public static final String LCAT = "TiAod";
	@Kroll.constant
	public static final int STATION_DLF = 3;
	@Kroll.constant
	public static final int STATION_KULTUR = 4;
	@Kroll.constant
	public static final int STATION_NOVA = 1;
	KrollFunction onLoad;
	KrollFunction onError;
	String url;
	static HashMap<Integer,Dailyscheduler> dailyschedulers;   
	//static Dailyscheduler dlf;
	//static Dailyscheduler drk;
	
	private TiProperties appProperties;

	public AodModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		String EP = "\"http://www.deutschlandfunk.de/programmvorschau";
		dlf = new Dailyscheduler(EP+".281.de.rss");
		drk = new Dailyscheduler(EP+".282.de.rss");
	}
	
}
